version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # - pip3 install pytest
      - pip3 install -r tests/requirements.txt
  build:
    commands:
      - echo 'Building...'
      - python -m pytest tests/unit --junitxml=reports/unit-report.xml
      - aws cloudformation package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file output.yml
      # - aws cloudformation deploy --template-file output.yml --s3-bucket $S3_BUCKET --stack-name $STACKNAME --capabilities CAPABILITY_IAM --region $REGION --parameter-overrides Env=$ENV
      - aws cloudformation deploy --template-file output.yml --s3-bucket $S3_BUCKET --stack-name $STACKNAME --capabilities CAPABILITY_IAM --region $REGION
      - aws cloudformation describe-stacks --stack-name $STACKNAME
reports:
  pytest_reports:
    files:
      - reports/unit-report.xml
    file-format: JUNITXML
