version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # - pip3 install pytest
      - pip3 install -r tests/requirements.txt
  build:
    commands:
      - echo 'Building...'
      - python -m pytest tests/unit --junitxml=reports/unit-report.xml
      - wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install
      - sam build
      - sam deploy --no-confirm-changeset

reports:
  pytest_reports:
    files:
      - reports/unit-report.xml
    file-format: JUNITXML
