version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "oura-score-get-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14reg3kal9csh"
s3_prefix = "oura-score-get-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
